name: ios build
on:
  push:
    tags:
      - 'v*'
env:
  APP_CONFIG: ${{ secrets.APP_CONFIG }}
  EXPO_CONFIG: ${{ secrets.EXPO_CONFIG }}
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v1
      - name: Cache node_modules
        uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-memoir-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys:
            ${{ runner.os }}-memoir-
      - name: Install node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Create .env file
        run: echo $APP_CONFIG | base64 --decode -i > ./.env
      - name: Create ./scripts/appConfig.js file
        run: echo $EXPO_CONFIG | base64 --decode -i > ./scripts/appConfig.js
      - name: codegen
        run: yarn codegen
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - run: yarn ios:build:ci
        env:
          EXPO_APPLE_ID: ${{ secrets.APPLE_ID }}
          EXPO_APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}